import {
  FaDownload,
  FaFileInvoiceDollar,
  FaCheckCircle,
} from "react-icons/fa";

const invoices = [
  {
    id: 1,
    invoice: "INV-2026-1001",
    customer: "Rahul Verma",
    amount: "₹3,200",
    date: "01 Aug 2026",
    status: "Paid",
  },
  {
    id: 2,
    invoice: "INV-2026-1002",
    customer: "Priya Sharma",
    amount: "₹2,800",
    date: "02 Aug 2026",
    status: "Paid",
  },
  {
    id: 3,
    invoice: "INV-2026-1003",
    customer: "Amit Yadav",
    amount: "₹3,000",
    date: "03 Aug 2026",
    status: "Paid",
  },
  {
    id: 4,
    invoice: "INV-2026-1004",
    customer: "Neha Singh",
    amount: "₹3,450",
    date: "04 Aug 2026",
    status: "Paid",
  },
  {
    id: 5,
    invoice: "INV-2026-1005",
    customer: "Vikas Patel",
    amount: "₹2,950",
    date: "05 Aug 2026",
    status: "Paid",
  },
];

function InvoiceTable() {
  return (
    <section
      className="rounded-3xl p-8"
      style={{
        background: "var(--color-surface)",
        border: "1px solid var(--color-border)",
        boxShadow: "var(--shadow-lg)",
      }}
    >
      <div className="mb-8 flex items-center justify-between">

        <div>

          <h2
            className="text-3xl font-bold"
            style={{
              color: "var(--color-text-primary)",
            }}
          >
            Recent Invoices
          </h2>

          <p
            className="mt-2"
            style={{
              color: "var(--color-text-secondary)",
            }}
          >
            Latest payment invoices generated by the system.
          </p>

        </div>

      </div>

      <div className="overflow-x-auto">

        <table className="min-w-full">

          <thead
            style={{
              background: "var(--color-background)",
            }}
          >
            <tr>

              <th className="px-6 py-4 text-left">
                Invoice ID
              </th>

              <th className="px-6 py-4 text-left">
                Student
              </th>

              <th className="px-6 py-4 text-left">
                Amount
              </th>

              <th className="px-6 py-4 text-left">
                Date
              </th>

              <th className="px-6 py-4 text-center">
                Status
              </th>

              <th className="px-6 py-4 text-center">
                Action
              </th>

            </tr>
          </thead>

          <tbody>

            {invoices.map((invoice) => (
              <tr
                key={invoice.id}
                style={{
                  borderTop:
                    "1px solid var(--color-border)",
                }}
              >

                <td className="px-6 py-5">

                  <div className="flex items-center gap-3">

                    <FaFileInvoiceDollar
                      style={{
                        color:
                          "var(--color-primary)",
                      }}
                    />

                    {invoice.invoice}

                  </div>

                </td>

                <td className="px-6 py-5">
                  {invoice.customer}
                </td>

                <td className="px-6 py-5 font-bold">
                  {invoice.amount}
                </td>

                <td className="px-6 py-5">
                  {invoice.date}
                </td>

                <td className="px-6 py-5 text-center">

                  <span
                    className="inline-flex items-center gap-2 rounded-full px-4 py-2"
                    style={{
                      background:
                        "var(--color-success-subtle)",
                      color:
                        "var(--color-success)",
                    }}
                  >
                    <FaCheckCircle />

                    {invoice.status}

                  </span>

                </td>

                <td className="px-6 py-5 text-center">

                  <button
                    className="inline-flex items-center gap-2 rounded-xl px-4 py-2 font-semibold"
                    style={{
                      background:
                        "var(--color-primary-subtle)",
                      color:
                        "var(--color-primary)",
                    }}
                  >
                    <FaDownload />

                    Download

                  </button>

                </td>

              </tr>
            ))}

          </tbody>

        </table>

      </div>

    </section>
  );
}

export default InvoiceTable;